### PR TITLE
Google translated the strings_en xml. Only the chinese part is translated.

### PR DESCRIPTION
**Pull request by mdavid5**
I've reviewed the file after the translation and corrected the formatting mistakes made by the translation process.

### CODE REVIEW

**Comment by vivalaflam** [comment]
This is not the final version of the translation. I fixed all issues as I'm a native English speaker, and I translated chinese as well.

**Comment by vivalaflam** [comment]
I mean next version is gonna feature my english translation, which pretty much is similar to your thing, apart, I formatted the chinese translation manually, without Google translate

**Comment by mdavid5** [comment]
This sounds good :) I did't know there is somebody working on the translation who speaks Chinese. (Yes this version is a bit barbaric... but I've finished the "translation" in 30 minutes)

**Comment by vivalaflam** [comment]
There are indeed some minor grammar mistakes in the chinese terms of service, but the formatting is correct. (the file I uploaded is not uploadable because I used wordpad, but hopefully, the author will input the strings exactly how I wrote them.)

Also, one more thought, is to change the app's name.
change it from "car bluetooth fm" to something like RoidMi or Xiaomi RoidMi or something similar

**Comment by mdavid5** [comment]
I see you didn't fork the original repository :) (I guess you are not a coder guy) You can validate the xml you made with online tools too if you don't have any coding editor. Like this one: 
https://validator.w3.org/feed/#validate_by_input

If everything is ok with your translation then the only error this tool will say is this (because it expects html not a resource file):
line 2, column 0: Undefined root element: resources

**Comment by vivalaflam** [comment]
Actually I'm an IT engineer, at least I'm studying it :P
I just downloaded the xml and edited it with wordpad.
Last time I checked that was good enough for all the app translations I've done (android assistant being the most popular one)

**Comment by mdavid5** [comment]
Haha sorry :) Then why don't you make a fork modify the file and make a pull request? The author suggest that to contribute. This way he doesn't have to make things manually (the Travis CI builder will validate your work too)

**Comment by vivalaflam** [comment]
I made a github account just for this, havent actually gotten around on how to use it -- yet. no time

**Comment by ihortymoshenko** [comment]
@kkszysiu, I think this PR is no longer needed

P.S. Can you make the new release? Thanks!

**Pull request closed without merging**
