### PR TITLE
mifm 1.40 and other improvements

### PR DESCRIPTION
**Pull request by lszeremeta**

### CODE REVIEW

**Comment by kkszysiu** [comment]
Thank you!

**Comment by vivalaflam** [comment]
This doesn't have the English translation I provided, nor is it the latest apk...

latest version is 1.41

**Comment by kkszysiu** [comment]
@vivalaflam I will put your changes to English translation soon. Your text editor broke chinese characters to I need to backport your translation manually.

Also from where I can download 1.41 version?
On official page I see only 1.40 version :)

**Comment by vivalaflam** [comment]
@kkszysiu I have it, do you want a gdrive link?

**Comment by kkszysiu** [comment]
@vivalaflam sure, can you paste it there or send me as gdrive on MIUI forum?

Thanks!

**Comment by vivalaflam** [comment]
Also, I edited it with wordpad, is there any better editor so I can import it and have it ready for you?

**Comment by kkszysiu** [comment]
Don't worry, I can backport it :)

Next time you can use for example Notepad++ on Windows - that's pretty good and powerful editor :)

**Comment by kkszysiu** [comment]
@vivalaflam just sent me 1.41 on gdrive, please :+1:

**Comment by vivalaflam** [comment]
https://docs.google.com/uc?id=0B78_J-cKCfl_c0p3N2lLZDdWNWs&export=download

**Comment by kkszysiu** [comment]
Thanks!

**Comment by vivalaflam** [comment]
You're welcome.

I will also make a Greek translation.

Maybe in the future a German and an Italian too.
But that's in the future, as I have university to attend:)
Cheers.

**Comment by lszeremeta** [comment]
@vivalaflam Roidmi 1.41 app is not yet officially available as apk package. Latest version available to download from [roidmi.com](http://www.roidmi.com/downloadapp) is now 1.40, so I used that :-)

I also recommend [Notepad++](https://notepad-plus-plus.org/), if you are using Windows.

**Comment by vivalaflam** [comment]
So isn't what I sent you the v1.41?

**Comment by kkszysiu** [comment]
@vivalaflam wow, I see you're pretty multilingual. I'm trying to learn Tagalog at the moment but it's pretty hard.

I will update current translations with your one.

Anyway thanks guys for support and help @lszeremeta @vivalaflam :)

**Comment by vivalaflam** [comment]
I speak 6 languages :P
cool, I want to try it :p

**Comment by jonniex7** [comment]
Greece thank you gyus!!!

**Pull request merged**
